/**
 * Catálogo CUT (Código Único Territorial) de Chile: 16 regiones,
 * 56 provincias y 346 comunas. Fuente: SUBDERE, planilla oficial
 * de códigos únicos territoriales (actualización 2018-09-06,
 * vigente: 346 comunas). Los slugs de las 8 comunas piloto
 * (santiago, las-condes, providencia, vitacura, nunoa, maipu,
 * quilicura, pudahuel) se conservan.
 *
 * La jerarquía legal es Región / Provincia / Comuna.
 * En la UI el nivel medio se etiqueta "Provincia".
 */

export type SemillaComuna = {
  cut: string
  slug: string
  nombre: string
  region: string
  provincia: string
}

export const ORDEN_REGIONES = [
  'Región de Arica y Parinacota',
  'Región de Tarapacá',
  'Región de Antofagasta',
  'Región de Atacama',
  'Región de Coquimbo',
  'Región de Valparaíso',
  'Región Metropolitana',
  "Región del Libertador General Bernardo O'Higgins",
  'Región del Maule',
  'Región de Ñuble',
  'Región del Biobío',
  'Región de La Araucanía',
  'Región de Los Ríos',
  'Región de Los Lagos',
  'Región de Aysén',
  'Región de Magallanes',
] as const

export const COMUNAS_CHILE: SemillaComuna[] = [
  { cut: '15101', slug: 'arica', nombre: 'Arica', region: 'Región de Arica y Parinacota', provincia: 'Arica' },
  { cut: '15102', slug: 'camarones', nombre: 'Camarones', region: 'Región de Arica y Parinacota', provincia: 'Arica' },
  { cut: '15202', slug: 'general-lagos', nombre: 'General Lagos', region: 'Región de Arica y Parinacota', provincia: 'Parinacota' },
  { cut: '15201', slug: 'putre', nombre: 'Putre', region: 'Región de Arica y Parinacota', provincia: 'Parinacota' },
  { cut: '01107', slug: 'alto-hospicio', nombre: 'Alto Hospicio', region: 'Región de Tarapacá', provincia: 'Iquique' },
  { cut: '01101', slug: 'iquique', nombre: 'Iquique', region: 'Región de Tarapacá', provincia: 'Iquique' },
  { cut: '01402', slug: 'camina', nombre: 'Camiña', region: 'Región de Tarapacá', provincia: 'Tamarugal' },
  { cut: '01403', slug: 'colchane', nombre: 'Colchane', region: 'Región de Tarapacá', provincia: 'Tamarugal' },
  { cut: '01404', slug: 'huara', nombre: 'Huara', region: 'Región de Tarapacá', provincia: 'Tamarugal' },
  { cut: '01405', slug: 'pica', nombre: 'Pica', region: 'Región de Tarapacá', provincia: 'Tamarugal' },
  { cut: '01401', slug: 'pozo-almonte', nombre: 'Pozo Almonte', region: 'Región de Tarapacá', provincia: 'Tamarugal' },
  { cut: '02101', slug: 'antofagasta', nombre: 'Antofagasta', region: 'Región de Antofagasta', provincia: 'Antofagasta' },
  { cut: '02102', slug: 'mejillones', nombre: 'Mejillones', region: 'Región de Antofagasta', provincia: 'Antofagasta' },
  { cut: '02103', slug: 'sierra-gorda', nombre: 'Sierra Gorda', region: 'Región de Antofagasta', provincia: 'Antofagasta' },
  { cut: '02104', slug: 'taltal', nombre: 'Taltal', region: 'Región de Antofagasta', provincia: 'Antofagasta' },
  { cut: '02201', slug: 'calama', nombre: 'Calama', region: 'Región de Antofagasta', provincia: 'El Loa' },
  { cut: '02202', slug: 'ollague', nombre: 'Ollagüe', region: 'Región de Antofagasta', provincia: 'El Loa' },
  { cut: '02203', slug: 'san-pedro-de-atacama', nombre: 'San Pedro de Atacama', region: 'Región de Antofagasta', provincia: 'El Loa' },
  { cut: '02302', slug: 'maria-elena', nombre: 'María Elena', region: 'Región de Antofagasta', provincia: 'Tocopilla' },
  { cut: '02301', slug: 'tocopilla', nombre: 'Tocopilla', region: 'Región de Antofagasta', provincia: 'Tocopilla' },
  { cut: '03201', slug: 'chanaral', nombre: 'Chañaral', region: 'Región de Atacama', provincia: 'Chañaral' },
  { cut: '03202', slug: 'diego-de-almagro', nombre: 'Diego de Almagro', region: 'Región de Atacama', provincia: 'Chañaral' },
  { cut: '03102', slug: 'caldera', nombre: 'Caldera', region: 'Región de Atacama', provincia: 'Copiapó' },
  { cut: '03101', slug: 'copiapo', nombre: 'Copiapó', region: 'Región de Atacama', provincia: 'Copiapó' },
  { cut: '03103', slug: 'tierra-amarilla', nombre: 'Tierra Amarilla', region: 'Región de Atacama', provincia: 'Copiapó' },
  { cut: '03302', slug: 'alto-del-carmen', nombre: 'Alto del Carmen', region: 'Región de Atacama', provincia: 'Huasco' },
  { cut: '03303', slug: 'freirina', nombre: 'Freirina', region: 'Región de Atacama', provincia: 'Huasco' },
  { cut: '03304', slug: 'huasco', nombre: 'Huasco', region: 'Región de Atacama', provincia: 'Huasco' },
  { cut: '03301', slug: 'vallenar', nombre: 'Vallenar', region: 'Región de Atacama', provincia: 'Huasco' },
  { cut: '04202', slug: 'canela', nombre: 'Canela', region: 'Región de Coquimbo', provincia: 'Choapa' },
  { cut: '04201', slug: 'illapel', nombre: 'Illapel', region: 'Región de Coquimbo', provincia: 'Choapa' },
  { cut: '04203', slug: 'los-vilos', nombre: 'Los Vilos', region: 'Región de Coquimbo', provincia: 'Choapa' },
  { cut: '04204', slug: 'salamanca', nombre: 'Salamanca', region: 'Región de Coquimbo', provincia: 'Choapa' },
  { cut: '04103', slug: 'andacollo', nombre: 'Andacollo', region: 'Región de Coquimbo', provincia: 'Elqui' },
  { cut: '04102', slug: 'coquimbo', nombre: 'Coquimbo', region: 'Región de Coquimbo', provincia: 'Elqui' },
  { cut: '04104', slug: 'la-higuera', nombre: 'La Higuera', region: 'Región de Coquimbo', provincia: 'Elqui' },
  { cut: '04101', slug: 'la-serena', nombre: 'La Serena', region: 'Región de Coquimbo', provincia: 'Elqui' },
  { cut: '04105', slug: 'paiguano', nombre: 'Paiguano', region: 'Región de Coquimbo', provincia: 'Elqui' },
  { cut: '04106', slug: 'vicuna', nombre: 'Vicuña', region: 'Región de Coquimbo', provincia: 'Elqui' },
  { cut: '04302', slug: 'combarbala', nombre: 'Combarbalá', region: 'Región de Coquimbo', provincia: 'Limarí' },
  { cut: '04303', slug: 'monte-patria', nombre: 'Monte Patria', region: 'Región de Coquimbo', provincia: 'Limarí' },
  { cut: '04301', slug: 'ovalle', nombre: 'Ovalle', region: 'Región de Coquimbo', provincia: 'Limarí' },
  { cut: '04304', slug: 'punitaqui', nombre: 'Punitaqui', region: 'Región de Coquimbo', provincia: 'Limarí' },
  { cut: '04305', slug: 'rio-hurtado', nombre: 'Río Hurtado', region: 'Región de Coquimbo', provincia: 'Limarí' },
  { cut: '05201', slug: 'isla-de-pascua', nombre: 'Isla de Pascua', region: 'Región de Valparaíso', provincia: 'Isla de Pascua' },
  { cut: '05302', slug: 'calle-larga', nombre: 'Calle Larga', region: 'Región de Valparaíso', provincia: 'Los Andes' },
  { cut: '05301', slug: 'los-andes', nombre: 'Los Andes', region: 'Región de Valparaíso', provincia: 'Los Andes' },
  { cut: '05303', slug: 'rinconada', nombre: 'Rinconada', region: 'Región de Valparaíso', provincia: 'Los Andes' },
  { cut: '05304', slug: 'san-esteban', nombre: 'San Esteban', region: 'Región de Valparaíso', provincia: 'Los Andes' },
  { cut: '05802', slug: 'limache', nombre: 'Limache', region: 'Región de Valparaíso', provincia: 'Marga Marga' },
  { cut: '05803', slug: 'olmue', nombre: 'Olmué', region: 'Región de Valparaíso', provincia: 'Marga Marga' },
  { cut: '05801', slug: 'quilpue', nombre: 'Quilpué', region: 'Región de Valparaíso', provincia: 'Marga Marga' },
  { cut: '05804', slug: 'villa-alemana', nombre: 'Villa Alemana', region: 'Región de Valparaíso', provincia: 'Marga Marga' },
  { cut: '05402', slug: 'cabildo', nombre: 'Cabildo', region: 'Región de Valparaíso', provincia: 'Petorca' },
  { cut: '05401', slug: 'la-ligua', nombre: 'La Ligua', region: 'Región de Valparaíso', provincia: 'Petorca' },
  { cut: '05403', slug: 'papudo', nombre: 'Papudo', region: 'Región de Valparaíso', provincia: 'Petorca' },
  { cut: '05404', slug: 'petorca', nombre: 'Petorca', region: 'Región de Valparaíso', provincia: 'Petorca' },
  { cut: '05405', slug: 'zapallar', nombre: 'Zapallar', region: 'Región de Valparaíso', provincia: 'Petorca' },
  { cut: '05502', slug: 'calera', nombre: 'Calera', region: 'Región de Valparaíso', provincia: 'Quillota' },
  { cut: '05503', slug: 'hijuelas', nombre: 'Hijuelas', region: 'Región de Valparaíso', provincia: 'Quillota' },
  { cut: '05504', slug: 'la-cruz', nombre: 'La Cruz', region: 'Región de Valparaíso', provincia: 'Quillota' },
  { cut: '05506', slug: 'nogales', nombre: 'Nogales', region: 'Región de Valparaíso', provincia: 'Quillota' },
  { cut: '05501', slug: 'quillota', nombre: 'Quillota', region: 'Región de Valparaíso', provincia: 'Quillota' },
  { cut: '05602', slug: 'algarrobo', nombre: 'Algarrobo', region: 'Región de Valparaíso', provincia: 'San Antonio' },
  { cut: '05603', slug: 'cartagena', nombre: 'Cartagena', region: 'Región de Valparaíso', provincia: 'San Antonio' },
  { cut: '05604', slug: 'el-quisco', nombre: 'El Quisco', region: 'Región de Valparaíso', provincia: 'San Antonio' },
  { cut: '05605', slug: 'el-tabo', nombre: 'El Tabo', region: 'Región de Valparaíso', provincia: 'San Antonio' },
  { cut: '05601', slug: 'san-antonio', nombre: 'San Antonio', region: 'Región de Valparaíso', provincia: 'San Antonio' },
  { cut: '05606', slug: 'santo-domingo', nombre: 'Santo Domingo', region: 'Región de Valparaíso', provincia: 'San Antonio' },
  { cut: '05702', slug: 'catemu', nombre: 'Catemu', region: 'Región de Valparaíso', provincia: 'San Felipe de Aconcagua' },
  { cut: '05703', slug: 'llaillay', nombre: 'Llaillay', region: 'Región de Valparaíso', provincia: 'San Felipe de Aconcagua' },
  { cut: '05704', slug: 'panquehue', nombre: 'Panquehue', region: 'Región de Valparaíso', provincia: 'San Felipe de Aconcagua' },
  { cut: '05705', slug: 'putaendo', nombre: 'Putaendo', region: 'Región de Valparaíso', provincia: 'San Felipe de Aconcagua' },
  { cut: '05701', slug: 'san-felipe', nombre: 'San Felipe', region: 'Región de Valparaíso', provincia: 'San Felipe de Aconcagua' },
  { cut: '05706', slug: 'santa-maria', nombre: 'Santa María', region: 'Región de Valparaíso', provincia: 'San Felipe de Aconcagua' },
  { cut: '05102', slug: 'casablanca', nombre: 'Casablanca', region: 'Región de Valparaíso', provincia: 'Valparaíso' },
  { cut: '05103', slug: 'concon', nombre: 'Concón', region: 'Región de Valparaíso', provincia: 'Valparaíso' },
  { cut: '05104', slug: 'juan-fernandez', nombre: 'Juan Fernández', region: 'Región de Valparaíso', provincia: 'Valparaíso' },
  { cut: '05105', slug: 'puchuncavi', nombre: 'Puchuncaví', region: 'Región de Valparaíso', provincia: 'Valparaíso' },
  { cut: '05107', slug: 'quintero', nombre: 'Quintero', region: 'Región de Valparaíso', provincia: 'Valparaíso' },
  { cut: '05101', slug: 'valparaiso', nombre: 'Valparaíso', region: 'Región de Valparaíso', provincia: 'Valparaíso' },
  { cut: '05109', slug: 'vina-del-mar', nombre: 'Viña del Mar', region: 'Región de Valparaíso', provincia: 'Valparaíso' },
  { cut: '13301', slug: 'colina', nombre: 'Colina', region: 'Región Metropolitana', provincia: 'Chacabuco' },
  { cut: '13302', slug: 'lampa', nombre: 'Lampa', region: 'Región Metropolitana', provincia: 'Chacabuco' },
  { cut: '13303', slug: 'tiltil', nombre: 'Tiltil', region: 'Región Metropolitana', provincia: 'Chacabuco' },
  { cut: '13202', slug: 'pirque', nombre: 'Pirque', region: 'Región Metropolitana', provincia: 'Cordillera' },
  { cut: '13201', slug: 'puente-alto', nombre: 'Puente Alto', region: 'Región Metropolitana', provincia: 'Cordillera' },
  { cut: '13203', slug: 'san-jose-de-maipo', nombre: 'San José de Maipo', region: 'Región Metropolitana', provincia: 'Cordillera' },
  { cut: '13402', slug: 'buin', nombre: 'Buin', region: 'Región Metropolitana', provincia: 'Maipo' },
  { cut: '13403', slug: 'calera-de-tango', nombre: 'Calera de Tango', region: 'Región Metropolitana', provincia: 'Maipo' },
  { cut: '13404', slug: 'paine', nombre: 'Paine', region: 'Región Metropolitana', provincia: 'Maipo' },
  { cut: '13401', slug: 'san-bernardo', nombre: 'San Bernardo', region: 'Región Metropolitana', provincia: 'Maipo' },
  { cut: '13502', slug: 'alhue', nombre: 'Alhué', region: 'Región Metropolitana', provincia: 'Melipilla' },
  { cut: '13503', slug: 'curacavi', nombre: 'Curacaví', region: 'Región Metropolitana', provincia: 'Melipilla' },
  { cut: '13504', slug: 'maria-pinto', nombre: 'María Pinto', region: 'Región Metropolitana', provincia: 'Melipilla' },
  { cut: '13501', slug: 'melipilla', nombre: 'Melipilla', region: 'Región Metropolitana', provincia: 'Melipilla' },
  { cut: '13505', slug: 'san-pedro', nombre: 'San Pedro', region: 'Región Metropolitana', provincia: 'Melipilla' },
  { cut: '13102', slug: 'cerrillos', nombre: 'Cerrillos', region: 'Región Metropolitana', provincia: 'Santiago' },
  { cut: '13103', slug: 'cerro-navia', nombre: 'Cerro Navia', region: 'Región Metropolitana', provincia: 'Santiago' },
  { cut: '13104', slug: 'conchali', nombre: 'Conchalí', region: 'Región Metropolitana', provincia: 'Santiago' },
  { cut: '13105', slug: 'el-bosque', nombre: 'El Bosque', region: 'Región Metropolitana', provincia: 'Santiago' },
  { cut: '13106', slug: 'estacion-central', nombre: 'Estación Central', region: 'Región Metropolitana', provincia: 'Santiago' },
  { cut: '13107', slug: 'huechuraba', nombre: 'Huechuraba', region: 'Región Metropolitana', provincia: 'Santiago' },
  { cut: '13108', slug: 'independencia', nombre: 'Independencia', region: 'Región Metropolitana', provincia: 'Santiago' },
  { cut: '13109', slug: 'la-cisterna', nombre: 'La Cisterna', region: 'Región Metropolitana', provincia: 'Santiago' },
  { cut: '13110', slug: 'la-florida', nombre: 'La Florida', region: 'Región Metropolitana', provincia: 'Santiago' },
  { cut: '13111', slug: 'la-granja', nombre: 'La Granja', region: 'Región Metropolitana', provincia: 'Santiago' },
  { cut: '13112', slug: 'la-pintana', nombre: 'La Pintana', region: 'Región Metropolitana', provincia: 'Santiago' },
  { cut: '13113', slug: 'la-reina', nombre: 'La Reina', region: 'Región Metropolitana', provincia: 'Santiago' },
  { cut: '13114', slug: 'las-condes', nombre: 'Las Condes', region: 'Región Metropolitana', provincia: 'Santiago' },
  { cut: '13115', slug: 'lo-barnechea', nombre: 'Lo Barnechea', region: 'Región Metropolitana', provincia: 'Santiago' },
  { cut: '13116', slug: 'lo-espejo', nombre: 'Lo Espejo', region: 'Región Metropolitana', provincia: 'Santiago' },
  { cut: '13117', slug: 'lo-prado', nombre: 'Lo Prado', region: 'Región Metropolitana', provincia: 'Santiago' },
  { cut: '13118', slug: 'macul', nombre: 'Macul', region: 'Región Metropolitana', provincia: 'Santiago' },
  { cut: '13119', slug: 'maipu', nombre: 'Maipú', region: 'Región Metropolitana', provincia: 'Santiago' },
  { cut: '13121', slug: 'pedro-aguirre-cerda', nombre: 'Pedro Aguirre Cerda', region: 'Región Metropolitana', provincia: 'Santiago' },
  { cut: '13122', slug: 'penalolen', nombre: 'Peñalolén', region: 'Región Metropolitana', provincia: 'Santiago' },
  { cut: '13123', slug: 'providencia', nombre: 'Providencia', region: 'Región Metropolitana', provincia: 'Santiago' },
  { cut: '13124', slug: 'pudahuel', nombre: 'Pudahuel', region: 'Región Metropolitana', provincia: 'Santiago' },
  { cut: '13125', slug: 'quilicura', nombre: 'Quilicura', region: 'Región Metropolitana', provincia: 'Santiago' },
  { cut: '13126', slug: 'quinta-normal', nombre: 'Quinta Normal', region: 'Región Metropolitana', provincia: 'Santiago' },
  { cut: '13127', slug: 'recoleta', nombre: 'Recoleta', region: 'Región Metropolitana', provincia: 'Santiago' },
  { cut: '13128', slug: 'renca', nombre: 'Renca', region: 'Región Metropolitana', provincia: 'Santiago' },
  { cut: '13129', slug: 'san-joaquin', nombre: 'San Joaquín', region: 'Región Metropolitana', provincia: 'Santiago' },
  { cut: '13130', slug: 'san-miguel', nombre: 'San Miguel', region: 'Región Metropolitana', provincia: 'Santiago' },
  { cut: '13131', slug: 'san-ramon', nombre: 'San Ramón', region: 'Región Metropolitana', provincia: 'Santiago' },
  { cut: '13101', slug: 'santiago', nombre: 'Santiago', region: 'Región Metropolitana', provincia: 'Santiago' },
  { cut: '13132', slug: 'vitacura', nombre: 'Vitacura', region: 'Región Metropolitana', provincia: 'Santiago' },
  { cut: '13120', slug: 'nunoa', nombre: 'Ñuñoa', region: 'Región Metropolitana', provincia: 'Santiago' },
  { cut: '13602', slug: 'el-monte', nombre: 'El Monte', region: 'Región Metropolitana', provincia: 'Talagante' },
  { cut: '13603', slug: 'isla-de-maipo', nombre: 'Isla de Maipo', region: 'Región Metropolitana', provincia: 'Talagante' },
  { cut: '13604', slug: 'padre-hurtado', nombre: 'Padre Hurtado', region: 'Región Metropolitana', provincia: 'Talagante' },
  { cut: '13605', slug: 'penaflor', nombre: 'Peñaflor', region: 'Región Metropolitana', provincia: 'Talagante' },
  { cut: '13601', slug: 'talagante', nombre: 'Talagante', region: 'Región Metropolitana', provincia: 'Talagante' },
  { cut: '06102', slug: 'codegua', nombre: 'Codegua', region: 'Región del Libertador General Bernardo O\'Higgins', provincia: 'Cachapoal' },
  { cut: '06103', slug: 'coinco', nombre: 'Coinco', region: 'Región del Libertador General Bernardo O\'Higgins', provincia: 'Cachapoal' },
  { cut: '06104', slug: 'coltauco', nombre: 'Coltauco', region: 'Región del Libertador General Bernardo O\'Higgins', provincia: 'Cachapoal' },
  { cut: '06105', slug: 'donihue', nombre: 'Doñihue', region: 'Región del Libertador General Bernardo O\'Higgins', provincia: 'Cachapoal' },
  { cut: '06106', slug: 'graneros', nombre: 'Graneros', region: 'Región del Libertador General Bernardo O\'Higgins', provincia: 'Cachapoal' },
  { cut: '06107', slug: 'las-cabras', nombre: 'Las Cabras', region: 'Región del Libertador General Bernardo O\'Higgins', provincia: 'Cachapoal' },
  { cut: '06108', slug: 'machali', nombre: 'Machalí', region: 'Región del Libertador General Bernardo O\'Higgins', provincia: 'Cachapoal' },
  { cut: '06109', slug: 'malloa', nombre: 'Malloa', region: 'Región del Libertador General Bernardo O\'Higgins', provincia: 'Cachapoal' },
  { cut: '06110', slug: 'mostazal', nombre: 'Mostazal', region: 'Región del Libertador General Bernardo O\'Higgins', provincia: 'Cachapoal' },
  { cut: '06111', slug: 'olivar', nombre: 'Olivar', region: 'Región del Libertador General Bernardo O\'Higgins', provincia: 'Cachapoal' },
  { cut: '06112', slug: 'peumo', nombre: 'Peumo', region: 'Región del Libertador General Bernardo O\'Higgins', provincia: 'Cachapoal' },
  { cut: '06113', slug: 'pichidegua', nombre: 'Pichidegua', region: 'Región del Libertador General Bernardo O\'Higgins', provincia: 'Cachapoal' },
  { cut: '06114', slug: 'quinta-de-tilcoco', nombre: 'Quinta de Tilcoco', region: 'Región del Libertador General Bernardo O\'Higgins', provincia: 'Cachapoal' },
  { cut: '06101', slug: 'rancagua', nombre: 'Rancagua', region: 'Región del Libertador General Bernardo O\'Higgins', provincia: 'Cachapoal' },
  { cut: '06115', slug: 'rengo', nombre: 'Rengo', region: 'Región del Libertador General Bernardo O\'Higgins', provincia: 'Cachapoal' },
  { cut: '06116', slug: 'requinoa', nombre: 'Requínoa', region: 'Región del Libertador General Bernardo O\'Higgins', provincia: 'Cachapoal' },
  { cut: '06117', slug: 'san-vicente', nombre: 'San Vicente', region: 'Región del Libertador General Bernardo O\'Higgins', provincia: 'Cachapoal' },
  { cut: '06202', slug: 'la-estrella', nombre: 'La Estrella', region: 'Región del Libertador General Bernardo O\'Higgins', provincia: 'Cardenal Caro' },
  { cut: '06203', slug: 'litueche', nombre: 'Litueche', region: 'Región del Libertador General Bernardo O\'Higgins', provincia: 'Cardenal Caro' },
  { cut: '06204', slug: 'marchihue', nombre: 'Marchihue', region: 'Región del Libertador General Bernardo O\'Higgins', provincia: 'Cardenal Caro' },
  { cut: '06205', slug: 'navidad', nombre: 'Navidad', region: 'Región del Libertador General Bernardo O\'Higgins', provincia: 'Cardenal Caro' },
  { cut: '06206', slug: 'paredones', nombre: 'Paredones', region: 'Región del Libertador General Bernardo O\'Higgins', provincia: 'Cardenal Caro' },
  { cut: '06201', slug: 'pichilemu', nombre: 'Pichilemu', region: 'Región del Libertador General Bernardo O\'Higgins', provincia: 'Cardenal Caro' },
  { cut: '06303', slug: 'chimbarongo', nombre: 'Chimbarongo', region: 'Región del Libertador General Bernardo O\'Higgins', provincia: 'Colchagua' },
  { cut: '06302', slug: 'chepica', nombre: 'Chépica', region: 'Región del Libertador General Bernardo O\'Higgins', provincia: 'Colchagua' },
  { cut: '06304', slug: 'lolol', nombre: 'Lolol', region: 'Región del Libertador General Bernardo O\'Higgins', provincia: 'Colchagua' },
  { cut: '06305', slug: 'nancagua', nombre: 'Nancagua', region: 'Región del Libertador General Bernardo O\'Higgins', provincia: 'Colchagua' },
  { cut: '06306', slug: 'palmilla', nombre: 'Palmilla', region: 'Región del Libertador General Bernardo O\'Higgins', provincia: 'Colchagua' },
  { cut: '06307', slug: 'peralillo', nombre: 'Peralillo', region: 'Región del Libertador General Bernardo O\'Higgins', provincia: 'Colchagua' },
  { cut: '06308', slug: 'placilla', nombre: 'Placilla', region: 'Región del Libertador General Bernardo O\'Higgins', provincia: 'Colchagua' },
  { cut: '06309', slug: 'pumanque', nombre: 'Pumanque', region: 'Región del Libertador General Bernardo O\'Higgins', provincia: 'Colchagua' },
  { cut: '06301', slug: 'san-fernando', nombre: 'San Fernando', region: 'Región del Libertador General Bernardo O\'Higgins', provincia: 'Colchagua' },
  { cut: '06310', slug: 'santa-cruz', nombre: 'Santa Cruz', region: 'Región del Libertador General Bernardo O\'Higgins', provincia: 'Colchagua' },
  { cut: '07201', slug: 'cauquenes', nombre: 'Cauquenes', region: 'Región del Maule', provincia: 'Cauquenes' },
  { cut: '07202', slug: 'chanco', nombre: 'Chanco', region: 'Región del Maule', provincia: 'Cauquenes' },
  { cut: '07203', slug: 'pelluhue', nombre: 'Pelluhue', region: 'Región del Maule', provincia: 'Cauquenes' },
  { cut: '07301', slug: 'curico', nombre: 'Curicó', region: 'Región del Maule', provincia: 'Curicó' },
  { cut: '07302', slug: 'hualane', nombre: 'Hualañé', region: 'Región del Maule', provincia: 'Curicó' },
  { cut: '07303', slug: 'licanten', nombre: 'Licantén', region: 'Región del Maule', provincia: 'Curicó' },
  { cut: '07304', slug: 'molina', nombre: 'Molina', region: 'Región del Maule', provincia: 'Curicó' },
  { cut: '07305', slug: 'rauco', nombre: 'Rauco', region: 'Región del Maule', provincia: 'Curicó' },
  { cut: '07306', slug: 'romeral', nombre: 'Romeral', region: 'Región del Maule', provincia: 'Curicó' },
  { cut: '07307', slug: 'sagrada-familia', nombre: 'Sagrada Familia', region: 'Región del Maule', provincia: 'Curicó' },
  { cut: '07308', slug: 'teno', nombre: 'Teno', region: 'Región del Maule', provincia: 'Curicó' },
  { cut: '07309', slug: 'vichuquen', nombre: 'Vichuquén', region: 'Región del Maule', provincia: 'Curicó' },
  { cut: '07402', slug: 'colbun', nombre: 'Colbún', region: 'Región del Maule', provincia: 'Linares' },
  { cut: '07401', slug: 'linares', nombre: 'Linares', region: 'Región del Maule', provincia: 'Linares' },
  { cut: '07403', slug: 'longavi', nombre: 'Longaví', region: 'Región del Maule', provincia: 'Linares' },
  { cut: '07404', slug: 'parral', nombre: 'Parral', region: 'Región del Maule', provincia: 'Linares' },
  { cut: '07405', slug: 'retiro', nombre: 'Retiro', region: 'Región del Maule', provincia: 'Linares' },
  { cut: '07406', slug: 'san-javier', nombre: 'San Javier', region: 'Región del Maule', provincia: 'Linares' },
  { cut: '07407', slug: 'villa-alegre', nombre: 'Villa Alegre', region: 'Región del Maule', provincia: 'Linares' },
  { cut: '07408', slug: 'yerbas-buenas', nombre: 'Yerbas Buenas', region: 'Región del Maule', provincia: 'Linares' },
  { cut: '07102', slug: 'constitucion', nombre: 'Constitución', region: 'Región del Maule', provincia: 'Talca' },
  { cut: '07103', slug: 'curepto', nombre: 'Curepto', region: 'Región del Maule', provincia: 'Talca' },
  { cut: '07104', slug: 'empedrado', nombre: 'Empedrado', region: 'Región del Maule', provincia: 'Talca' },
  { cut: '07105', slug: 'maule', nombre: 'Maule', region: 'Región del Maule', provincia: 'Talca' },
  { cut: '07106', slug: 'pelarco', nombre: 'Pelarco', region: 'Región del Maule', provincia: 'Talca' },
  { cut: '07107', slug: 'pencahue', nombre: 'Pencahue', region: 'Región del Maule', provincia: 'Talca' },
  { cut: '07108', slug: 'rio-claro', nombre: 'Río Claro', region: 'Región del Maule', provincia: 'Talca' },
  { cut: '07109', slug: 'san-clemente', nombre: 'San Clemente', region: 'Región del Maule', provincia: 'Talca' },
  { cut: '07110', slug: 'san-rafael', nombre: 'San Rafael', region: 'Región del Maule', provincia: 'Talca' },
  { cut: '07101', slug: 'talca', nombre: 'Talca', region: 'Región del Maule', provincia: 'Talca' },
  { cut: '16102', slug: 'bulnes', nombre: 'Bulnes', region: 'Región de Ñuble', provincia: 'Diguillín' },
  { cut: '16101', slug: 'chillan', nombre: 'Chillán', region: 'Región de Ñuble', provincia: 'Diguillín' },
  { cut: '16103', slug: 'chillan-viejo', nombre: 'Chillán Viejo', region: 'Región de Ñuble', provincia: 'Diguillín' },
  { cut: '16104', slug: 'el-carmen', nombre: 'El Carmen', region: 'Región de Ñuble', provincia: 'Diguillín' },
  { cut: '16105', slug: 'pemuco', nombre: 'Pemuco', region: 'Región de Ñuble', provincia: 'Diguillín' },
  { cut: '16106', slug: 'pinto', nombre: 'Pinto', region: 'Región de Ñuble', provincia: 'Diguillín' },
  { cut: '16107', slug: 'quillon', nombre: 'Quillón', region: 'Región de Ñuble', provincia: 'Diguillín' },
  { cut: '16108', slug: 'san-ignacio', nombre: 'San Ignacio', region: 'Región de Ñuble', provincia: 'Diguillín' },
  { cut: '16109', slug: 'yungay', nombre: 'Yungay', region: 'Región de Ñuble', provincia: 'Diguillín' },
  { cut: '16202', slug: 'cobquecura', nombre: 'Cobquecura', region: 'Región de Ñuble', provincia: 'Itata' },
  { cut: '16203', slug: 'coelemu', nombre: 'Coelemu', region: 'Región de Ñuble', provincia: 'Itata' },
  { cut: '16204', slug: 'ninhue', nombre: 'Ninhue', region: 'Región de Ñuble', provincia: 'Itata' },
  { cut: '16205', slug: 'portezuelo', nombre: 'Portezuelo', region: 'Región de Ñuble', provincia: 'Itata' },
  { cut: '16201', slug: 'quirihue', nombre: 'Quirihue', region: 'Región de Ñuble', provincia: 'Itata' },
  { cut: '16206', slug: 'ranquil', nombre: 'Ranquil', region: 'Región de Ñuble', provincia: 'Itata' },
  { cut: '16207', slug: 'trehuaco', nombre: 'Trehuaco', region: 'Región de Ñuble', provincia: 'Itata' },
  { cut: '16302', slug: 'coihueco', nombre: 'Coihueco', region: 'Región de Ñuble', provincia: 'Punilla' },
  { cut: '16301', slug: 'san-carlos', nombre: 'San Carlos', region: 'Región de Ñuble', provincia: 'Punilla' },
  { cut: '16304', slug: 'san-fabian', nombre: 'San Fabián', region: 'Región de Ñuble', provincia: 'Punilla' },
  { cut: '16305', slug: 'san-nicolas', nombre: 'San Nicolás', region: 'Región de Ñuble', provincia: 'Punilla' },
  { cut: '16303', slug: 'niquen', nombre: 'Ñiquén', region: 'Región de Ñuble', provincia: 'Punilla' },
  { cut: '08202', slug: 'arauco', nombre: 'Arauco', region: 'Región del Biobío', provincia: 'Arauco' },
  { cut: '08203', slug: 'canete', nombre: 'Cañete', region: 'Región del Biobío', provincia: 'Arauco' },
  { cut: '08204', slug: 'contulmo', nombre: 'Contulmo', region: 'Región del Biobío', provincia: 'Arauco' },
  { cut: '08205', slug: 'curanilahue', nombre: 'Curanilahue', region: 'Región del Biobío', provincia: 'Arauco' },
  { cut: '08201', slug: 'lebu', nombre: 'Lebu', region: 'Región del Biobío', provincia: 'Arauco' },
  { cut: '08206', slug: 'los-alamos', nombre: 'Los Álamos', region: 'Región del Biobío', provincia: 'Arauco' },
  { cut: '08207', slug: 'tirua', nombre: 'Tirúa', region: 'Región del Biobío', provincia: 'Arauco' },
  { cut: '08314', slug: 'alto-biobio', nombre: 'Alto Biobío', region: 'Región del Biobío', provincia: 'Biobío' },
  { cut: '08302', slug: 'antuco', nombre: 'Antuco', region: 'Región del Biobío', provincia: 'Biobío' },
  { cut: '08303', slug: 'cabrero', nombre: 'Cabrero', region: 'Región del Biobío', provincia: 'Biobío' },
  { cut: '08304', slug: 'laja', nombre: 'Laja', region: 'Región del Biobío', provincia: 'Biobío' },
  { cut: '08301', slug: 'los-angeles', nombre: 'Los Ángeles', region: 'Región del Biobío', provincia: 'Biobío' },
  { cut: '08305', slug: 'mulchen', nombre: 'Mulchén', region: 'Región del Biobío', provincia: 'Biobío' },
  { cut: '08306', slug: 'nacimiento', nombre: 'Nacimiento', region: 'Región del Biobío', provincia: 'Biobío' },
  { cut: '08307', slug: 'negrete', nombre: 'Negrete', region: 'Región del Biobío', provincia: 'Biobío' },
  { cut: '08308', slug: 'quilaco', nombre: 'Quilaco', region: 'Región del Biobío', provincia: 'Biobío' },
  { cut: '08309', slug: 'quilleco', nombre: 'Quilleco', region: 'Región del Biobío', provincia: 'Biobío' },
  { cut: '08310', slug: 'san-rosendo', nombre: 'San Rosendo', region: 'Región del Biobío', provincia: 'Biobío' },
  { cut: '08311', slug: 'santa-barbara', nombre: 'Santa Bárbara', region: 'Región del Biobío', provincia: 'Biobío' },
  { cut: '08312', slug: 'tucapel', nombre: 'Tucapel', region: 'Región del Biobío', provincia: 'Biobío' },
  { cut: '08313', slug: 'yumbel', nombre: 'Yumbel', region: 'Región del Biobío', provincia: 'Biobío' },
  { cut: '08103', slug: 'chiguayante', nombre: 'Chiguayante', region: 'Región del Biobío', provincia: 'Concepción' },
  { cut: '08101', slug: 'concepcion', nombre: 'Concepción', region: 'Región del Biobío', provincia: 'Concepción' },
  { cut: '08102', slug: 'coronel', nombre: 'Coronel', region: 'Región del Biobío', provincia: 'Concepción' },
  { cut: '08104', slug: 'florida', nombre: 'Florida', region: 'Región del Biobío', provincia: 'Concepción' },
  { cut: '08112', slug: 'hualpen', nombre: 'Hualpén', region: 'Región del Biobío', provincia: 'Concepción' },
  { cut: '08105', slug: 'hualqui', nombre: 'Hualqui', region: 'Región del Biobío', provincia: 'Concepción' },
  { cut: '08106', slug: 'lota', nombre: 'Lota', region: 'Región del Biobío', provincia: 'Concepción' },
  { cut: '08107', slug: 'penco', nombre: 'Penco', region: 'Región del Biobío', provincia: 'Concepción' },
  { cut: '08108', slug: 'san-pedro-de-la-paz', nombre: 'San Pedro de la Paz', region: 'Región del Biobío', provincia: 'Concepción' },
  { cut: '08109', slug: 'santa-juana', nombre: 'Santa Juana', region: 'Región del Biobío', provincia: 'Concepción' },
  { cut: '08110', slug: 'talcahuano', nombre: 'Talcahuano', region: 'Región del Biobío', provincia: 'Concepción' },
  { cut: '08111', slug: 'tome', nombre: 'Tomé', region: 'Región del Biobío', provincia: 'Concepción' },
  { cut: '09102', slug: 'carahue', nombre: 'Carahue', region: 'Región de La Araucanía', provincia: 'Cautín' },
  { cut: '09121', slug: 'cholchol', nombre: 'Cholchol', region: 'Región de La Araucanía', provincia: 'Cautín' },
  { cut: '09103', slug: 'cunco', nombre: 'Cunco', region: 'Región de La Araucanía', provincia: 'Cautín' },
  { cut: '09104', slug: 'curarrehue', nombre: 'Curarrehue', region: 'Región de La Araucanía', provincia: 'Cautín' },
  { cut: '09105', slug: 'freire', nombre: 'Freire', region: 'Región de La Araucanía', provincia: 'Cautín' },
  { cut: '09106', slug: 'galvarino', nombre: 'Galvarino', region: 'Región de La Araucanía', provincia: 'Cautín' },
  { cut: '09107', slug: 'gorbea', nombre: 'Gorbea', region: 'Región de La Araucanía', provincia: 'Cautín' },
  { cut: '09108', slug: 'lautaro', nombre: 'Lautaro', region: 'Región de La Araucanía', provincia: 'Cautín' },
  { cut: '09109', slug: 'loncoche', nombre: 'Loncoche', region: 'Región de La Araucanía', provincia: 'Cautín' },
  { cut: '09110', slug: 'melipeuco', nombre: 'Melipeuco', region: 'Región de La Araucanía', provincia: 'Cautín' },
  { cut: '09111', slug: 'nueva-imperial', nombre: 'Nueva Imperial', region: 'Región de La Araucanía', provincia: 'Cautín' },
  { cut: '09112', slug: 'padre-las-casas', nombre: 'Padre Las Casas', region: 'Región de La Araucanía', provincia: 'Cautín' },
  { cut: '09113', slug: 'perquenco', nombre: 'Perquenco', region: 'Región de La Araucanía', provincia: 'Cautín' },
  { cut: '09114', slug: 'pitrufquen', nombre: 'Pitrufquén', region: 'Región de La Araucanía', provincia: 'Cautín' },
  { cut: '09115', slug: 'pucon', nombre: 'Pucón', region: 'Región de La Araucanía', provincia: 'Cautín' },
  { cut: '09116', slug: 'saavedra', nombre: 'Saavedra', region: 'Región de La Araucanía', provincia: 'Cautín' },
  { cut: '09101', slug: 'temuco', nombre: 'Temuco', region: 'Región de La Araucanía', provincia: 'Cautín' },
  { cut: '09117', slug: 'teodoro-schmidt', nombre: 'Teodoro Schmidt', region: 'Región de La Araucanía', provincia: 'Cautín' },
  { cut: '09118', slug: 'tolten', nombre: 'Toltén', region: 'Región de La Araucanía', provincia: 'Cautín' },
  { cut: '09119', slug: 'vilcun', nombre: 'Vilcún', region: 'Región de La Araucanía', provincia: 'Cautín' },
  { cut: '09120', slug: 'villarrica', nombre: 'Villarrica', region: 'Región de La Araucanía', provincia: 'Cautín' },
  { cut: '09201', slug: 'angol', nombre: 'Angol', region: 'Región de La Araucanía', provincia: 'Malleco' },
  { cut: '09202', slug: 'collipulli', nombre: 'Collipulli', region: 'Región de La Araucanía', provincia: 'Malleco' },
  { cut: '09203', slug: 'curacautin', nombre: 'Curacautín', region: 'Región de La Araucanía', provincia: 'Malleco' },
  { cut: '09204', slug: 'ercilla', nombre: 'Ercilla', region: 'Región de La Araucanía', provincia: 'Malleco' },
  { cut: '09205', slug: 'lonquimay', nombre: 'Lonquimay', region: 'Región de La Araucanía', provincia: 'Malleco' },
  { cut: '09206', slug: 'los-sauces', nombre: 'Los Sauces', region: 'Región de La Araucanía', provincia: 'Malleco' },
  { cut: '09207', slug: 'lumaco', nombre: 'Lumaco', region: 'Región de La Araucanía', provincia: 'Malleco' },
  { cut: '09208', slug: 'puren', nombre: 'Purén', region: 'Región de La Araucanía', provincia: 'Malleco' },
  { cut: '09209', slug: 'renaico', nombre: 'Renaico', region: 'Región de La Araucanía', provincia: 'Malleco' },
  { cut: '09210', slug: 'traiguen', nombre: 'Traiguén', region: 'Región de La Araucanía', provincia: 'Malleco' },
  { cut: '09211', slug: 'victoria', nombre: 'Victoria', region: 'Región de La Araucanía', provincia: 'Malleco' },
  { cut: '14202', slug: 'futrono', nombre: 'Futrono', region: 'Región de Los Ríos', provincia: 'Ranco' },
  { cut: '14201', slug: 'la-union', nombre: 'La Unión', region: 'Región de Los Ríos', provincia: 'Ranco' },
  { cut: '14203', slug: 'lago-ranco', nombre: 'Lago Ranco', region: 'Región de Los Ríos', provincia: 'Ranco' },
  { cut: '14204', slug: 'rio-bueno', nombre: 'Río Bueno', region: 'Región de Los Ríos', provincia: 'Ranco' },
  { cut: '14102', slug: 'corral', nombre: 'Corral', region: 'Región de Los Ríos', provincia: 'Valdivia' },
  { cut: '14103', slug: 'lanco', nombre: 'Lanco', region: 'Región de Los Ríos', provincia: 'Valdivia' },
  { cut: '14104', slug: 'los-lagos', nombre: 'Los Lagos', region: 'Región de Los Ríos', provincia: 'Valdivia' },
  { cut: '14106', slug: 'mariquina', nombre: 'Mariquina', region: 'Región de Los Ríos', provincia: 'Valdivia' },
  { cut: '14105', slug: 'mafil', nombre: 'Máfil', region: 'Región de Los Ríos', provincia: 'Valdivia' },
  { cut: '14107', slug: 'paillaco', nombre: 'Paillaco', region: 'Región de Los Ríos', provincia: 'Valdivia' },
  { cut: '14108', slug: 'panguipulli', nombre: 'Panguipulli', region: 'Región de Los Ríos', provincia: 'Valdivia' },
  { cut: '14101', slug: 'valdivia', nombre: 'Valdivia', region: 'Región de Los Ríos', provincia: 'Valdivia' },
  { cut: '10202', slug: 'ancud', nombre: 'Ancud', region: 'Región de Los Lagos', provincia: 'Chiloé' },
  { cut: '10201', slug: 'castro', nombre: 'Castro', region: 'Región de Los Lagos', provincia: 'Chiloé' },
  { cut: '10203', slug: 'chonchi', nombre: 'Chonchi', region: 'Región de Los Lagos', provincia: 'Chiloé' },
  { cut: '10204', slug: 'curaco-de-velez', nombre: 'Curaco de Vélez', region: 'Región de Los Lagos', provincia: 'Chiloé' },
  { cut: '10205', slug: 'dalcahue', nombre: 'Dalcahue', region: 'Región de Los Lagos', provincia: 'Chiloé' },
  { cut: '10206', slug: 'puqueldon', nombre: 'Puqueldón', region: 'Región de Los Lagos', provincia: 'Chiloé' },
  { cut: '10207', slug: 'queilen', nombre: 'Queilén', region: 'Región de Los Lagos', provincia: 'Chiloé' },
  { cut: '10208', slug: 'quellon', nombre: 'Quellón', region: 'Región de Los Lagos', provincia: 'Chiloé' },
  { cut: '10209', slug: 'quemchi', nombre: 'Quemchi', region: 'Región de Los Lagos', provincia: 'Chiloé' },
  { cut: '10210', slug: 'quinchao', nombre: 'Quinchao', region: 'Región de Los Lagos', provincia: 'Chiloé' },
  { cut: '10102', slug: 'calbuco', nombre: 'Calbuco', region: 'Región de Los Lagos', provincia: 'Llanquihue' },
  { cut: '10103', slug: 'cochamo', nombre: 'Cochamó', region: 'Región de Los Lagos', provincia: 'Llanquihue' },
  { cut: '10104', slug: 'fresia', nombre: 'Fresia', region: 'Región de Los Lagos', provincia: 'Llanquihue' },
  { cut: '10105', slug: 'frutillar', nombre: 'Frutillar', region: 'Región de Los Lagos', provincia: 'Llanquihue' },
  { cut: '10107', slug: 'llanquihue', nombre: 'Llanquihue', region: 'Región de Los Lagos', provincia: 'Llanquihue' },
  { cut: '10106', slug: 'los-muermos', nombre: 'Los Muermos', region: 'Región de Los Lagos', provincia: 'Llanquihue' },
  { cut: '10108', slug: 'maullin', nombre: 'Maullín', region: 'Región de Los Lagos', provincia: 'Llanquihue' },
  { cut: '10101', slug: 'puerto-montt', nombre: 'Puerto Montt', region: 'Región de Los Lagos', provincia: 'Llanquihue' },
  { cut: '10109', slug: 'puerto-varas', nombre: 'Puerto Varas', region: 'Región de Los Lagos', provincia: 'Llanquihue' },
  { cut: '10301', slug: 'osorno', nombre: 'Osorno', region: 'Región de Los Lagos', provincia: 'Osorno' },
  { cut: '10302', slug: 'puerto-octay', nombre: 'Puerto Octay', region: 'Región de Los Lagos', provincia: 'Osorno' },
  { cut: '10303', slug: 'purranque', nombre: 'Purranque', region: 'Región de Los Lagos', provincia: 'Osorno' },
  { cut: '10304', slug: 'puyehue', nombre: 'Puyehue', region: 'Región de Los Lagos', provincia: 'Osorno' },
  { cut: '10305', slug: 'rio-negro', nombre: 'Río Negro', region: 'Región de Los Lagos', provincia: 'Osorno' },
  { cut: '10306', slug: 'san-juan-de-la-costa', nombre: 'San Juan de la Costa', region: 'Región de Los Lagos', provincia: 'Osorno' },
  { cut: '10307', slug: 'san-pablo', nombre: 'San Pablo', region: 'Región de Los Lagos', provincia: 'Osorno' },
  { cut: '10401', slug: 'chaiten', nombre: 'Chaitén', region: 'Región de Los Lagos', provincia: 'Palena' },
  { cut: '10402', slug: 'futaleufu', nombre: 'Futaleufú', region: 'Región de Los Lagos', provincia: 'Palena' },
  { cut: '10403', slug: 'hualaihue', nombre: 'Hualaihué', region: 'Región de Los Lagos', provincia: 'Palena' },
  { cut: '10404', slug: 'palena', nombre: 'Palena', region: 'Región de Los Lagos', provincia: 'Palena' },
  { cut: '11201', slug: 'aysen', nombre: 'Aysén', region: 'Región de Aysén', provincia: 'Aysén' },
  { cut: '11202', slug: 'cisnes', nombre: 'Cisnes', region: 'Región de Aysén', provincia: 'Aysén' },
  { cut: '11203', slug: 'guaitecas', nombre: 'Guaitecas', region: 'Región de Aysén', provincia: 'Aysén' },
  { cut: '11301', slug: 'cochrane', nombre: 'Cochrane', region: 'Región de Aysén', provincia: 'Capitán Prat' },
  { cut: '11302', slug: 'o-higgins', nombre: 'O\'Higgins', region: 'Región de Aysén', provincia: 'Capitán Prat' },
  { cut: '11303', slug: 'tortel', nombre: 'Tortel', region: 'Región de Aysén', provincia: 'Capitán Prat' },
  { cut: '11101', slug: 'coyhaique', nombre: 'Coyhaique', region: 'Región de Aysén', provincia: 'Coyhaique' },
  { cut: '11102', slug: 'lago-verde', nombre: 'Lago Verde', region: 'Región de Aysén', provincia: 'Coyhaique' },
  { cut: '11401', slug: 'chile-chico', nombre: 'Chile Chico', region: 'Región de Aysén', provincia: 'General Carrera' },
  { cut: '11402', slug: 'rio-ibanez', nombre: 'Río Ibáñez', region: 'Región de Aysén', provincia: 'General Carrera' },
  { cut: '12202', slug: 'antartica', nombre: 'Antártica', region: 'Región de Magallanes', provincia: 'Antártica Chilena' },
  { cut: '12201', slug: 'cabo-de-hornos', nombre: 'Cabo de Hornos', region: 'Región de Magallanes', provincia: 'Antártica Chilena' },
  { cut: '12102', slug: 'laguna-blanca', nombre: 'Laguna Blanca', region: 'Región de Magallanes', provincia: 'Magallanes' },
  { cut: '12101', slug: 'punta-arenas', nombre: 'Punta Arenas', region: 'Región de Magallanes', provincia: 'Magallanes' },
  { cut: '12103', slug: 'rio-verde', nombre: 'Río Verde', region: 'Región de Magallanes', provincia: 'Magallanes' },
  { cut: '12104', slug: 'san-gregorio', nombre: 'San Gregorio', region: 'Región de Magallanes', provincia: 'Magallanes' },
  { cut: '12301', slug: 'porvenir', nombre: 'Porvenir', region: 'Región de Magallanes', provincia: 'Tierra del Fuego' },
  { cut: '12302', slug: 'primavera', nombre: 'Primavera', region: 'Región de Magallanes', provincia: 'Tierra del Fuego' },
  { cut: '12303', slug: 'timaukel', nombre: 'Timaukel', region: 'Región de Magallanes', provincia: 'Tierra del Fuego' },
  { cut: '12401', slug: 'natales', nombre: 'Natales', region: 'Región de Magallanes', provincia: 'Última Esperanza' },
  { cut: '12402', slug: 'torres-del-paine', nombre: 'Torres del Paine', region: 'Región de Magallanes', provincia: 'Última Esperanza' },
]

