-- Ola hogar / empresa / asesoría: 17 rubros VENTA + páginas piloto.
-- Aditivo: no borra, no toca créditos, no reactiva "prueba-e2e".
-- ON CONFLICT (slug) DO NOTHING: si la fila ya existe, se respeta.

INSERT INTO "Rubro" (
  id,
  slug,
  nombre,
  "nombrePlural",
  descripcion,
  modo,
  activo,
  orden,
  "precioExclusivoClp",
  "precioCompartidoClp",
  "camposFormulario",
  "contenidoSeo",
  "createdAt",
  "updatedAt"
) VALUES
  (
    'rubro_gasfiteria',
    'gasfiteria',
    'Gasfitería',
    'Gasfitería',
    'Reparaciones, instalaciones y urgencias de gasfitería en casa o empresa.',
    'VENTA',
    true,
    20,
    12000,
    5000,
    '[{"nombre":"tipo_trabajo","etiqueta":"¿Qué necesitas?","tipo":"select","requerido":true,"opciones":[{"valor":"reparacion","etiqueta":"Una reparación"},{"valor":"instalacion","etiqueta":"Una instalación"},{"valor":"urgencia","etiqueta":"Una urgencia (fuga o corte)"},{"valor":"otro","etiqueta":"Otro"}]},{"nombre":"plazo","etiqueta":"¿Para cuándo lo necesitas?","tipo":"select","requerido":true,"opciones":[{"valor":"urgente","etiqueta":"Lo antes posible"},{"valor":"esta_semana","etiqueta":"Esta semana"},{"valor":"este_mes","etiqueta":"Este mes"},{"valor":"cotizando","etiqueta":"Solo estoy cotizando"}]},{"nombre":"detalle","etiqueta":"Cuéntanos un poco más","tipo":"textarea","requerido":false,"placeholder":"¿Cañería, llave, calefont, WC? ¿Casa o local?"}]'::jsonb,
    '{"intro":"Di qué se echó a perder y te contactan gasfiteres que atienden tu comuna. Sirve para casa o empresa. Sin cuenta para empezar. Tú no pagas.","porQue":"En gasfitería la urgencia y el tipo de arreglo cambian el precio. Mientras más claro lo dejes, más firme es la cotización."}'::jsonb,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'rubro_electricista',
    'electricista',
    'Electricista',
    'Electricista',
    'Instalaciones, fallas y tableros eléctricos para casa o empresa.',
    'VENTA',
    true,
    21,
    12000,
    5000,
    '[{"nombre":"tipo_trabajo","etiqueta":"¿Qué necesitas?","tipo":"select","requerido":true,"opciones":[{"valor":"falla","etiqueta":"Una falla o un corte"},{"valor":"instalacion","etiqueta":"Una instalación nueva"},{"valor":"tablero","etiqueta":"Tablero o ampliación"},{"valor":"otro","etiqueta":"Otro"}]},{"nombre":"plazo","etiqueta":"¿Para cuándo lo necesitas?","tipo":"select","requerido":true,"opciones":[{"valor":"urgente","etiqueta":"Lo antes posible"},{"valor":"esta_semana","etiqueta":"Esta semana"},{"valor":"este_mes","etiqueta":"Este mes"},{"valor":"cotizando","etiqueta":"Solo estoy cotizando"}]},{"nombre":"detalle","etiqueta":"Cuéntanos un poco más","tipo":"textarea","requerido":false,"placeholder":"¿Casa, depto o local? ¿Qué está fallando?"}]'::jsonb,
    '{"intro":"Cuéntanos la falla o lo que hay que instalar. Te contactan electricistas de tu comuna. Casa o empresa. Sin cuenta para empezar. Tú no pagas.","porQue":"Un enchufe no se cotiza igual que un tablero. Mientras más detalle, más útil es la visita."}'::jsonb,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'rubro_destape',
    'destape',
    'Destape y alcantarillado',
    'Destape y alcantarillado',
    'Destape de cañerías, WC y alcantarillado en casa o empresa.',
    'VENTA',
    true,
    22,
    10000,
    4000,
    '[{"nombre":"tipo_trabajo","etiqueta":"¿Qué está tapado?","tipo":"select","requerido":true,"opciones":[{"valor":"wc","etiqueta":"WC"},{"valor":"lavaplatos","etiqueta":"Lavaplatos o ducha"},{"valor":"alcantarillado","etiqueta":"Alcantarillado o cámara"},{"valor":"otro","etiqueta":"Otro"}]},{"nombre":"plazo","etiqueta":"¿Para cuándo lo necesitas?","tipo":"select","requerido":true,"opciones":[{"valor":"urgente","etiqueta":"Lo antes posible"},{"valor":"esta_semana","etiqueta":"Esta semana"},{"valor":"este_mes","etiqueta":"Este mes"},{"valor":"cotizando","etiqueta":"Solo estoy cotizando"}]},{"nombre":"detalle","etiqueta":"Cuéntanos un poco más","tipo":"textarea","requerido":false,"placeholder":"¿Desde cuándo? ¿Hay agua en el piso?"}]'::jsonb,
    '{"intro":"Di qué está tapado y te contactan empresas de destape de tu comuna. Casa o empresa. Sin cuenta para empezar. Tú no pagas.","porQue":"Un WC no se cotiza igual que una cámara. La urgencia manda el precio."}'::jsonb,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'rubro_pintura',
    'pintura',
    'Pintura',
    'Pintura',
    'Pintura interior y exterior para casa, depto o local.',
    'VENTA',
    true,
    23,
    15000,
    6000,
    '[{"nombre":"tipo_trabajo","etiqueta":"¿Qué hay que pintar?","tipo":"select","requerido":true,"opciones":[{"valor":"interior","etiqueta":"Interior"},{"valor":"exterior","etiqueta":"Exterior"},{"valor":"ambos","etiqueta":"Interior y exterior"},{"valor":"otro","etiqueta":"Otro"}]},{"nombre":"plazo","etiqueta":"¿Para cuándo lo necesitas?","tipo":"select","requerido":true,"opciones":[{"valor":"urgente","etiqueta":"Lo antes posible"},{"valor":"esta_semana","etiqueta":"Esta semana"},{"valor":"este_mes","etiqueta":"Este mes"},{"valor":"cotizando","etiqueta":"Solo estoy cotizando"}]},{"nombre":"detalle","etiqueta":"Cuéntanos un poco más","tipo":"textarea","requerido":false,"placeholder":"¿Cuántos metros o piezas? ¿Casa, depto o local?"}]'::jsonb,
    '{"intro":"Di qué hay que pintar y te contactan pintores de tu comuna. Casa o empresa. Sin cuenta para empezar. Tú no pagas.","porQue":"Los metros y si es interior o fachada cambian el valor. Una pieza no se cotiza igual que un local."}'::jsonb,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'rubro_remodelaciones',
    'remodelaciones',
    'Remodelaciones',
    'Remodelaciones',
    'Obras menores y remodelaciones de casa, depto o local.',
    'VENTA',
    true,
    24,
    25000,
    10000,
    '[{"nombre":"tipo_trabajo","etiqueta":"¿Qué quieres remodelar?","tipo":"select","requerido":true,"opciones":[{"valor":"bano","etiqueta":"Baño"},{"valor":"cocina","etiqueta":"Cocina"},{"valor":"ampliacion","etiqueta":"Ampliación o pieza"},{"valor":"otro","etiqueta":"Otro"}]},{"nombre":"plazo","etiqueta":"¿Para cuándo lo necesitas?","tipo":"select","requerido":true,"opciones":[{"valor":"urgente","etiqueta":"Lo antes posible"},{"valor":"esta_semana","etiqueta":"Esta semana"},{"valor":"este_mes","etiqueta":"Este mes"},{"valor":"cotizando","etiqueta":"Solo estoy cotizando"}]},{"nombre":"detalle","etiqueta":"Cuéntanos un poco más","tipo":"textarea","requerido":false,"placeholder":"¿Casa, depto o local? ¿Ya tienes idea del alcance?"}]'::jsonb,
    '{"intro":"Cuéntanos el alcance y te contactan maestros y empresas de remodelación de tu comuna. Casa o empresa. Sin cuenta para empezar. Tú no pagas.","porQue":"Un baño no se cotiza igual que una ampliación. El alcance manda el precio."}'::jsonb,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'rubro_cerrajeria',
    'cerrajeria',
    'Cerrajero',
    'Cerrajero',
    'Apertura, cambio de cerraduras y copias de llave.',
    'VENTA',
    true,
    25,
    8000,
    3000,
    '[{"nombre":"tipo_trabajo","etiqueta":"¿Qué necesitas?","tipo":"select","requerido":true,"opciones":[{"valor":"apertura","etiqueta":"Abrir una puerta o un auto"},{"valor":"cambio","etiqueta":"Cambiar cerradura"},{"valor":"copia","etiqueta":"Copia de llaves"},{"valor":"otro","etiqueta":"Otro"}]},{"nombre":"plazo","etiqueta":"¿Para cuándo lo necesitas?","tipo":"select","requerido":true,"opciones":[{"valor":"urgente","etiqueta":"Lo antes posible"},{"valor":"esta_semana","etiqueta":"Esta semana"},{"valor":"este_mes","etiqueta":"Este mes"},{"valor":"cotizando","etiqueta":"Solo estoy cotizando"}]},{"nombre":"detalle","etiqueta":"Cuéntanos un poco más","tipo":"textarea","requerido":false,"placeholder":"¿Casa, depto, local o auto?"}]'::jsonb,
    '{"intro":"Di si es apertura, cambio de chapa o copias. Te contactan cerrajeros de tu comuna. Sin cuenta para empezar. Tú no pagas.","porQue":"Una urgencia de madrugada no se cotiza igual que un cambio de chapa programado."}'::jsonb,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'rubro_tecnico_electrodomesticos',
    'tecnico-electrodomesticos',
    'Técnico de electrodomésticos',
    'Técnico de electrodomésticos',
    'Reparación de lavadoras, refrigeradores y otros electrodomésticos.',
    'VENTA',
    true,
    26,
    8000,
    3000,
    '[{"nombre":"tipo_equipo","etiqueta":"¿Qué equipo es?","tipo":"select","requerido":true,"opciones":[{"valor":"lavadora","etiqueta":"Lavadora o secadora"},{"valor":"refri","etiqueta":"Refrigerador"},{"valor":"lavavajillas","etiqueta":"Lavavajillas"},{"valor":"otro","etiqueta":"Otro"}]},{"nombre":"plazo","etiqueta":"¿Para cuándo lo necesitas?","tipo":"select","requerido":true,"opciones":[{"valor":"urgente","etiqueta":"Lo antes posible"},{"valor":"esta_semana","etiqueta":"Esta semana"},{"valor":"este_mes","etiqueta":"Este mes"},{"valor":"cotizando","etiqueta":"Solo estoy cotizando"}]},{"nombre":"detalle","etiqueta":"Cuéntanos un poco más","tipo":"textarea","requerido":false,"placeholder":"¿Qué marca y qué le pasa?"}]'::jsonb,
    '{"intro":"Di qué equipo falló y te contactan técnicos de tu comuna. Sin cuenta para empezar. Tú no pagas.","porQue":"La marca y el tipo de falla cambian el valor. Un diagnóstico no se cotiza igual que un cambio de motor."}'::jsonb,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'rubro_mudanzas',
    'mudanzas',
    'Mudanzas y fletes',
    'Mudanzas y fletes',
    'Mudanzas de casa o oficina y fletes dentro de Chile.',
    'VENTA',
    true,
    27,
    15000,
    6000,
    '[{"nombre":"tipo_servicio","etiqueta":"¿Qué necesitas?","tipo":"select","requerido":true,"opciones":[{"valor":"casa","etiqueta":"Mudanza de casa o depto"},{"valor":"oficina","etiqueta":"Mudanza de oficina"},{"valor":"flete","etiqueta":"Un flete puntual"},{"valor":"otro","etiqueta":"Otro"}]},{"nombre":"plazo","etiqueta":"¿Para cuándo lo necesitas?","tipo":"select","requerido":true,"opciones":[{"valor":"urgente","etiqueta":"Lo antes posible"},{"valor":"esta_semana","etiqueta":"Esta semana"},{"valor":"este_mes","etiqueta":"Este mes"},{"valor":"cotizando","etiqueta":"Solo estoy cotizando"}]},{"nombre":"detalle","etiqueta":"Cuéntanos un poco más","tipo":"textarea","requerido":false,"placeholder":"¿De dónde a dónde? ¿Pisos, ascensor, empaque?"}]'::jsonb,
    '{"intro":"Di origen, destino y si es casa u oficina. Te contactan empresas de mudanzas de tu comuna. Sin cuenta para empezar. Tú no pagas.","porQue":"Los pisos, el empaque y la distancia mandan. Un depto no se cotiza igual que una oficina."}'::jsonb,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'rubro_jardineria',
    'jardineria',
    'Jardinería',
    'Jardinería',
    'Mantención de jardines, podas y áreas verdes.',
    'VENTA',
    true,
    28,
    10000,
    4000,
    '[{"nombre":"tipo_trabajo","etiqueta":"¿Qué necesitas?","tipo":"select","requerido":true,"opciones":[{"valor":"mantencion","etiqueta":"Mantención periódica"},{"valor":"poda","etiqueta":"Poda"},{"valor":"diseno","etiqueta":"Diseño o instalación"},{"valor":"otro","etiqueta":"Otro"}]},{"nombre":"plazo","etiqueta":"¿Para cuándo lo necesitas?","tipo":"select","requerido":true,"opciones":[{"valor":"urgente","etiqueta":"Lo antes posible"},{"valor":"esta_semana","etiqueta":"Esta semana"},{"valor":"este_mes","etiqueta":"Este mes"},{"valor":"cotizando","etiqueta":"Solo estoy cotizando"}]},{"nombre":"detalle","etiqueta":"Cuéntanos un poco más","tipo":"textarea","requerido":false,"placeholder":"¿Casa, condominio o empresa? ¿Metros aproximados?"}]'::jsonb,
    '{"intro":"Cuéntanos el jardín y te contactan jardineros de tu comuna. Casa o empresa. Sin cuenta para empezar. Tú no pagas.","porQue":"Los metros y si es una visita o un contrato mensual cambian el precio."}'::jsonb,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'rubro_aseo_hogar',
    'aseo-hogar',
    'Aseo a domicilio',
    'Aseo a domicilio',
    'Aseo de casas y departamentos. Distinto del aseo de empresas y oficinas.',
    'VENTA',
    true,
    29,
    8000,
    3000,
    '[{"nombre":"tipo_servicio","etiqueta":"¿Qué aseo necesitas?","tipo":"select","requerido":true,"opciones":[{"valor":"por_hora","etiqueta":"Por horas, una vez"},{"valor":"periodico","etiqueta":"Periódico (semanal o quincenal)"},{"valor":"mudanza","etiqueta":"Aseo de mudanza o a fondo"},{"valor":"otro","etiqueta":"Otro"}]},{"nombre":"plazo","etiqueta":"¿Para cuándo lo necesitas?","tipo":"select","requerido":true,"opciones":[{"valor":"urgente","etiqueta":"Lo antes posible"},{"valor":"esta_semana","etiqueta":"Esta semana"},{"valor":"este_mes","etiqueta":"Este mes"},{"valor":"cotizando","etiqueta":"Solo estoy cotizando"}]},{"nombre":"detalle","etiqueta":"Cuéntanos un poco más","tipo":"textarea","requerido":false,"placeholder":"¿Casa o depto? ¿Metros o piezas?"}]'::jsonb,
    '{"intro":"Di si es una vez o periódico. Te contactan personas y empresas de aseo a domicilio en tu comuna. Esto no es aseo industrial: para oficinas usa Empresas de aseo. Tú no pagas.","porQue":"Las horas y si es a fondo o mantención cambian el valor. Un depto no se cotiza igual que una casa."}'::jsonb,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'rubro_cuidado_adulto_mayor',
    'cuidado-adulto-mayor',
    'Cuidado de adulto mayor',
    'Cuidado de adulto mayor',
    'Cuidadores a domicilio por horas o jornada.',
    'VENTA',
    true,
    30,
    20000,
    8000,
    '[{"nombre":"tipo_jornada","etiqueta":"¿Qué jornada necesitas?","tipo":"select","requerido":true,"opciones":[{"valor":"horas","etiqueta":"Algunas horas al día"},{"valor":"diurna","etiqueta":"Jornada de día"},{"valor":"24_7","etiqueta":"Día y noche"},{"valor":"otro","etiqueta":"Otro"}]},{"nombre":"plazo","etiqueta":"¿Para cuándo lo necesitas?","tipo":"select","requerido":true,"opciones":[{"valor":"urgente","etiqueta":"Lo antes posible"},{"valor":"esta_semana","etiqueta":"Esta semana"},{"valor":"este_mes","etiqueta":"Este mes"},{"valor":"cotizando","etiqueta":"Solo estoy cotizando"}]},{"nombre":"detalle","etiqueta":"Cuéntanos un poco más","tipo":"textarea","requerido":false,"placeholder":"¿Cuántos días a la semana? ¿Hay que ayudar con medicamentos o movilidad?"}]'::jsonb,
    '{"intro":"Cuéntanos la jornada y te contactan servicios de cuidado a domicilio en tu comuna. Sin cuenta para empezar. Tú no pagas.","porQue":"Las horas y el tipo de apoyo cambian el valor. Un turno diurno no se cotiza igual que un 24/7."}'::jsonb,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'rubro_contabilidad',
    'contabilidad',
    'Contabilidad',
    'Contabilidad',
    'Contadores para pymes: F29, remuneraciones y contabilidad mensual.',
    'VENTA',
    true,
    40,
    20000,
    8000,
    '[{"nombre":"tipo_servicio","etiqueta":"¿Qué necesitas?","tipo":"select","requerido":true,"opciones":[{"valor":"mensual","etiqueta":"Contabilidad mensual"},{"valor":"inicio","etiqueta":"Inicio de actividades"},{"valor":"remuneraciones","etiqueta":"Remuneraciones"},{"valor":"otro","etiqueta":"Otro"}]},{"nombre":"plazo","etiqueta":"¿Para cuándo lo necesitas?","tipo":"select","requerido":true,"opciones":[{"valor":"urgente","etiqueta":"Lo antes posible"},{"valor":"esta_semana","etiqueta":"Esta semana"},{"valor":"este_mes","etiqueta":"Este mes"},{"valor":"cotizando","etiqueta":"Solo estoy cotizando"}]},{"nombre":"detalle","etiqueta":"Cuéntanos un poco más","tipo":"textarea","requerido":false,"placeholder":"¿Pyme, sociedad o persona? ¿Ya facturas?"}]'::jsonb,
    '{"intro":"Di qué trámite o mes necesitas. Te contactan contadores que atienden tu comuna. Sin cuenta para empezar. Tú no pagas.","porQue":"El régimen y si hay remuneraciones cambian el valor. Un F29 no se cotiza igual que una nómina."}'::jsonb,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'rubro_marketing_digital',
    'marketing-digital',
    'Marketing digital',
    'Marketing digital',
    'Agencias y freelancers de pauta, redes y sitios web.',
    'VENTA',
    true,
    41,
    25000,
    10000,
    '[{"nombre":"tipo_servicio","etiqueta":"¿Qué necesitas?","tipo":"select","requerido":true,"opciones":[{"valor":"pauta","etiqueta":"Pauta (Google o Meta)"},{"valor":"redes","etiqueta":"Redes sociales"},{"valor":"web","etiqueta":"Sitio web"},{"valor":"otro","etiqueta":"Otro"}]},{"nombre":"plazo","etiqueta":"¿Para cuándo lo necesitas?","tipo":"select","requerido":true,"opciones":[{"valor":"urgente","etiqueta":"Lo antes posible"},{"valor":"esta_semana","etiqueta":"Esta semana"},{"valor":"este_mes","etiqueta":"Este mes"},{"valor":"cotizando","etiqueta":"Solo estoy cotizando"}]},{"nombre":"detalle","etiqueta":"Cuéntanos un poco más","tipo":"textarea","requerido":false,"placeholder":"¿Qué vendes y qué resultado buscas?"}]'::jsonb,
    '{"intro":"Cuéntanos el canal y te contactan agencias o freelancers de tu zona. Sin cuenta para empezar. Tú no pagas.","porQue":"Pauta no se cotiza igual que un sitio. El objetivo manda el precio."}'::jsonb,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'rubro_abogados',
    'abogados',
    'Abogados',
    'Abogados',
    'Asesoría legal laboral, civil, familia o empresa.',
    'VENTA',
    true,
    42,
    25000,
    10000,
    '[{"nombre":"tipo_asunto","etiqueta":"¿De qué se trata?","tipo":"select","requerido":true,"opciones":[{"valor":"laboral","etiqueta":"Laboral"},{"valor":"civil","etiqueta":"Civil o contratos"},{"valor":"familia","etiqueta":"Familia"},{"valor":"empresa","etiqueta":"Empresa o societario"},{"valor":"otro","etiqueta":"Otro"}]},{"nombre":"plazo","etiqueta":"¿Para cuándo lo necesitas?","tipo":"select","requerido":true,"opciones":[{"valor":"urgente","etiqueta":"Lo antes posible"},{"valor":"esta_semana","etiqueta":"Esta semana"},{"valor":"este_mes","etiqueta":"Este mes"},{"valor":"cotizando","etiqueta":"Solo estoy cotizando"}]},{"nombre":"detalle","etiqueta":"Cuéntanos un poco más","tipo":"textarea","requerido":false,"placeholder":"En una frase, sin datos sensibles de terceros."}]'::jsonb,
    '{"intro":"Di el tipo de asunto (sin contar el caso entero). Te contactan abogados que atienden tu comuna. Sin cuenta para empezar. Tú no pagas.","porQue":"Laboral no se cotiza igual que un contrato de empresa. El tipo de asunto manda."}'::jsonb,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'rubro_reclutamiento',
    'reclutamiento',
    'Reclutamiento',
    'Reclutamiento',
    'Búsqueda de personal y headhunting para empresas.',
    'VENTA',
    true,
    43,
    20000,
    8000,
    '[{"nombre":"tipo_busqueda","etiqueta":"¿Qué cargo buscas?","tipo":"select","requerido":true,"opciones":[{"valor":"operativo","etiqueta":"Cargo operativo o terreno"},{"valor":"admin","etiqueta":"Administrativo"},{"valor":"profesional","etiqueta":"Profesional o jefatura"},{"valor":"otro","etiqueta":"Otro"}]},{"nombre":"plazo","etiqueta":"¿Para cuándo lo necesitas?","tipo":"select","requerido":true,"opciones":[{"valor":"urgente","etiqueta":"Lo antes posible"},{"valor":"esta_semana","etiqueta":"Esta semana"},{"valor":"este_mes","etiqueta":"Este mes"},{"valor":"cotizando","etiqueta":"Solo estoy cotizando"}]},{"nombre":"detalle","etiqueta":"Cuéntanos un poco más","tipo":"textarea","requerido":false,"placeholder":"¿Ciudad, jornada y si es un cargo o varios?"}]'::jsonb,
    '{"intro":"Di el cargo y la comuna. Te contactan empresas de reclutamiento. Sin cuenta para empezar. Tú no pagas.","porQue":"Un cargo operativo no se cotiza igual que una jefatura. El perfil manda el valor."}'::jsonb,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'rubro_asesoria_financiera',
    'asesoria-financiera',
    'Créditos y asesoría financiera',
    'Créditos y asesoría financiera',
    'Asesores y corredores de crédito. Ternio no es un banco y no abre cuentas.',
    'VENTA',
    true,
    50,
    25000,
    10000,
    '[{"nombre":"tipo_asesoria","etiqueta":"¿Qué quieres evaluar?","tipo":"select","requerido":true,"opciones":[{"valor":"consumo","etiqueta":"Crédito de consumo"},{"valor":"hipotecario","etiqueta":"Crédito hipotecario"},{"valor":"refinanciar","etiqueta":"Refinanciar deudas"},{"valor":"pyme","etiqueta":"Crédito para mi empresa"},{"valor":"otro","etiqueta":"Otra asesoría"}]},{"nombre":"plazo","etiqueta":"¿Para cuándo lo necesitas?","tipo":"select","requerido":true,"opciones":[{"valor":"urgente","etiqueta":"Lo antes posible"},{"valor":"esta_semana","etiqueta":"Esta semana"},{"valor":"este_mes","etiqueta":"Este mes"},{"valor":"cotizando","etiqueta":"Solo estoy cotizando"}]},{"nombre":"detalle","etiqueta":"Cuéntanos un poco más","tipo":"textarea","requerido":false,"placeholder":"Sin inventar montos si no los tienes. Ternio solo te pasa con asesores."}]'::jsonb,
    '{"intro":"Cuéntanos qué quieres evaluar. Te contactan asesores y corredores de tu zona. Ternio no es un banco, no abre cuentas y no otorga créditos. Tú no pagas por cotizar.","porQue":"Un hipotecario no se cotiza igual que un consumo. El tipo de evaluación manda. Nadie aquí te abre una cuenta."}'::jsonb,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'rubro_seguros',
    'seguros',
    'Seguros',
    'Seguros',
    'Corredores de seguros de auto, hogar, vida o empresa. Ternio no vende pólizas.',
    'VENTA',
    true,
    51,
    15000,
    6000,
    '[{"nombre":"tipo_seguro","etiqueta":"¿Qué seguro buscas?","tipo":"select","requerido":true,"opciones":[{"valor":"auto","etiqueta":"Auto"},{"valor":"hogar","etiqueta":"Hogar"},{"valor":"vida_salud","etiqueta":"Vida o salud"},{"valor":"empresa","etiqueta":"Empresa"},{"valor":"otro","etiqueta":"Otro"}]},{"nombre":"plazo","etiqueta":"¿Para cuándo lo necesitas?","tipo":"select","requerido":true,"opciones":[{"valor":"urgente","etiqueta":"Lo antes posible"},{"valor":"esta_semana","etiqueta":"Esta semana"},{"valor":"este_mes","etiqueta":"Este mes"},{"valor":"cotizando","etiqueta":"Solo estoy cotizando"}]},{"nombre":"detalle","etiqueta":"Cuéntanos un poco más","tipo":"textarea","requerido":false,"placeholder":"Te contactan corredores. Ternio no emite pólizas."}]'::jsonb,
    '{"intro":"Di el tipo de seguro. Te contactan corredores que atienden tu comuna. Ternio no es una aseguradora y no vende pólizas. Tú no pagas por cotizar.","porQue":"Un SOAP no se cotiza igual que un seguro de empresa. El ramo manda. Nadie aquí te abre una cuenta bancaria."}'::jsonb,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  )
ON CONFLICT (slug) DO NOTHING;

INSERT INTO "RubroComuna" (
  id,
  "rubroId",
  "comunaId",
  activa,
  "createdAt",
  "updatedAt"
)
SELECT
  'rc_' || r.slug || '_' || c.slug,
  r.id,
  c.id,
  true,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
FROM "Rubro" r
CROSS JOIN "Comuna" c
WHERE r.slug IN ('gasfiteria', 'electricista', 'destape', 'pintura', 'remodelaciones', 'cerrajeria', 'tecnico-electrodomesticos', 'mudanzas', 'jardineria', 'aseo-hogar', 'cuidado-adulto-mayor', 'contabilidad', 'marketing-digital', 'abogados', 'reclutamiento', 'asesoria-financiera', 'seguros')
  AND r.slug <> 'prueba-e2e'
  AND c.slug IN ('santiago', 'las-condes', 'providencia', 'vitacura', 'nunoa', 'maipu', 'quilicura', 'pudahuel')
ON CONFLICT ("rubroId", "comunaId") DO NOTHING;
